#!/bin/bash -l

#$ -cwd
#$ -P bf528
#$ -j y
#$ -l h_rt=24:00:00 

module load salmon

echo "Running job $JOB_ID"
echo "Started: $(date +%F) $(date +%T)"
echo "Running in directory: $PWD"

DIR=/projectnb/bf528/project_4_scrnaseq/fastq/SRR387960

salmon alevin -l ISR -1 $DIR4_1.fastq.gz $DIR5_1.fastq.gz $DIR6_1.fastq.gz -2 $DIR4_2.fastq.gz $DIR5_2.fastq.gz $DIR6_2.fastq.gz -i transcript_index -p 10 -o alevin_output --tgMap map.tsv --whitelist whitelist.csv --end 5 --barcodeLength 19 --umiLength 6

echo "Job finished: $(date +%F) $(date +%T)"
